Repository PaulYH/GOATed_with_the_SAUCE-soen341project2023, pull requests merged in 2023-03, with the labels that each got.

#30 Job posting CRUD
  Sprints/Sprint 2/CSAPlatform/CSAPlatform/CSAPlatform.csproj
  Sprints/Sprint 2/CSAPlatform/CSAPlatform/Pages/JobPosting.razor
  Sprints/Sprint 2/CSAPlatform/CSAPlatform/Pages/Jobs.razor
  Sprints/Sprint 2/CSAPlatform/CSAPlatform/Pages/New.razor
  Sprints/Sprint 2/CSAPlatform/CSAPlatform/Program.cs
  Sprints/Sprint 2/CSAPlatform/DatabaseAccess/Data/JobPostService.cs
Labels: US-04

#52 UI design
  CSAPlatform/CSAPlatform/Areas/Identity/Pages/Account/Login.cshtml
  CSAPlatform/CSAPlatform/Areas/Identity/Pages/Account/Login.cshtml.cs
  CSAPlatform/CSAPlatform/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml
  CSAPlatform/CSAPlatform/Areas/Identity/Pages/_ValidationScriptsPartial.cshtml
  CSAPlatform/CSAPlatform/CSAPlatform.csproj
  CSAPlatform/CSAPlatform/Pages/Index.razor
  CSAPlatform/CSAPlatform/Pages/_Layout.cshtml
  CSAPlatform/CSAPlatform/Shared/MainLayout.razor
  CSAPlatform/CSAPlatform/_Imports.razor
  CSAPlatform/CSAPlatform/wwwroot/css/site.css
  CSAPlatform/CSAPlatform/wwwroot/lib/blazor-ui/swatches/default-ocean-blue.css
Labels: Task

#58 Email notification
  CSAPlatform/CSAPlatform/CSAPlatform.csproj
  CSAPlatform/CSAPlatform/Pages/StudentApplication.razor
  CSAPlatform/CSAPlatform/Program.cs
  CSAPlatform/DatabaseAccess/Data/EmailService.cs
  CSAPlatform/DatabaseAccess/Data/JobApplicationService.cs
  CSAPlatform/DatabaseAccess/DatabaseAccess.csproj
Labels: US-07
